function renderRegister(q=''){let rows=getRecords(),st=document.getElementById('statusFilter')?.value||'';if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));if(st)rows=rows.filter(x=>x.status===st);document.getElementById('register').innerHTML=rows.length?`<div class="table"><table><thead><tr><th>${tr('reference')}</th><th>${tr('project')}</th><th>${tr('value')}</th><th>${tr('date')}</th><th>${tr('status')}</th><th>${tr('actions')}</th></tr></thead><tbody>${rows.map(x=>`<tr class="data"><td>${x.reference}</td><td>${x.project}</td><td>${money(x.value)}</td><td>${x.date}</td><td>${statusBadge(x.status)}</td><td class="actionsCell"><button class="mini" onclick="editRecord('${x.id}')">${tr('edit')}</button> <button class="mini danger" onclick="deleteRecord('${x.id}')">${tr('delete')}</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="callout">${tr('noRecords')}</div>`}
function newRecord(){openRecordModal(null)}function editRecord(id){openRecordModal(getRecords().find(x=>x.id===id))}
function openRecordModal(row){const c=cfg(),isEdit=!!row;document.getElementById('modalTitle').textContent=isEdit?tr('edit'):tr('newRecord');document.getElementById('modalBody').innerHTML=`<div class="formgrid">${c.fields.map(([k,l,t])=>fieldHtml(k,l,t,row?.[k])).join('')}</div>`;document.getElementById('modalFoot').innerHTML=`<button class="btn exit" onclick="closeModal()">${tr('cancel')}</button><button class="btn primary" onclick="saveRecord('${row?.id||''}')">${tr('save')}</button>`;document.getElementById('modal').showModal()}
function fieldHtml(k,l,t,v=''){if(t==='select')return `<div class="field"><label>${l}</label><select id="f_${k}">${['Active','Pending','Approved','Rejected'].map(x=>`<option ${v===x?'selected':''} value="${x}">${statusText(x)}</option>`).join('')}</select></div>`;return `<div class="field"><label>${l}</label><input id="f_${k}" type="${t}" value="${v??''}"></div>`}
function saveRecord(id){const c=cfg(),obj={id:id||`${key()}-${Date.now()}`};c.fields.forEach(([k])=>obj[k]=document.getElementById(`f_${k}`).value);obj.value=Number(obj.value||0);let rows=getRecords();let ix=rows.findIndex(x=>x.id===id);if(ix>=0)rows[ix]=obj;else rows.unshift(obj);setRecords(rows);logAudit(id?'UPDATE':'INSERT',obj.reference);closeModal();renderWorkPanel();toast(tr('recordSaved'))}
function deleteRecord(id){let rows=getRecords(),r=rows.find(x=>x.id===id);setRecords(rows.filter(x=>x.id!==id));logAudit('DELETE',r?.reference||id);renderWorkPanel();toast(tr('recordDeleted'))}
function openApprovals(){let rows=getRecords();document.getElementById('modalTitle').textContent=tr('approvals');document.getElementById('modalBody').innerHTML=`<div class="table"><table><thead><tr><th>${tr('reference')}</th><th>${tr('project')}</th><th>${tr('status')}</th><th>${tr('actions')}</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.reference}</td><td>${x.project}</td><td>${statusBadge(x.status)}</td><td><button class="mini" onclick="setApproval('${x.id}','Approved')">${tr('approve')}</button> <button class="mini danger" onclick="setApproval('${x.id}','Rejected')">${tr('reject')}</button></td></tr>`).join('')}</tbody></table></div>`;document.getElementById('modalFoot').innerHTML=`<button class="btn exit" onclick="closeModal()">${tr('back')}</button>`;document.getElementById('modal').showModal()}
function setApproval(id,s){let rows=getRecords(),r=rows.find(x=>x.id===id);if(r)r.status=s;setRecords(rows);logAudit('APPROVAL',`${r?.reference} → ${s}`);openApprovals();renderWorkPanel();toast(tr('approvalUpdated'))}
function exportCsv(){const rows=getRecords(),headers=['reference','project','value','date','status'];const csv=[headers.join(','),...rows.map(r=>headers.map(h=>`"${String(r[h]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`PROGACTS-M${currentModule}-${currentWork+1}.csv`;a.click();URL.revokeObjectURL(a.href);logAudit('EXPORT',key());toast(tr('exported'))}
function logAudit(action,ref){let a=JSON.parse(localStorage.getItem('progacts_audit')||'[]');a.unshift({time:new Date().toISOString(),module:currentModule,work:currentWork,action,ref});localStorage.setItem('progacts_audit',JSON.stringify(a.slice(0,200)))}
function openAudit(){let a=JSON.parse(localStorage.getItem('progacts_audit')||'[]').filter(x=>x.module===currentModule&&x.work===currentWork);document.getElementById('modalTitle').textContent=tr('auditTrail');document.getElementById('modalBody').innerHTML=a.length?`<div class="timeline">${a.map(x=>`<div class="event"><b>${x.action} · ${x.ref}</b><p>${new Date(x.time).toLocaleString(lang==='ar'?'ar-AE':'en-GB')}</p></div>`).join('')}</div>`:`<div class="callout">${lang==='ar'?'لا توجد أحداث تدقيق بعد.':'No audit events yet.'}</div>`;document.getElementById('modalFoot').innerHTML=`<button class="btn exit" onclick="closeModal()">${tr('back')}</button>`;document.getElementById('modal').showModal()}
function closeModal(){document.getElementById('modal').close()}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function resetDemo(){localStorage.removeItem('progacts_records');localStorage.removeItem('progacts_audit');renderWorkPanel();toast(lang==='ar'?'تمت إعادة ضبط البيانات.':'Demo data reset.')}
function showControl(type,btn){active(btn);const journal=type==='journal';head(journal?tr('journal'):tr('audit'),journal?(lang==='ar'?'مرجع الترحيلات المحاسبية':'Backend posting reference'):(lang==='ar'?'من / ماذا / متى / القيمة السابقة':'Who / what / when / previous value'));let rows=journal?(lang==='ar'?[['شراء للمشروع','WIP — المشروع','الموردون / النقد','بدون أثر مخزون'],['دفعة مقدمة','النقد','إيراد مؤجل','التزام IFRS 15'],['اعتراف نسبة الإنجاز','ذمم غير مفوترة','إيراد المشروع','إقفال الفترة'],['استخدام معدات','WIP — المشروع','استرداد المعدات','بوابة التأمين'],['إقفال المشروع','تكلفة المشروع','WIP — المشروع','التسليم مطلوب']]:[['Project purchase','WIP — Project','AP / Cash','Zero inventory impact'],['Advance receipt','Cash','Deferred Revenue','IFRS 15 liability'],['PoC recognition','Unbilled Receivable','Project Revenue','Period close'],['Equipment usage','WIP — Project','Equipment Recovery','Insurance gated'],['Project closure','Project COGS','WIP — Project','Handover required']]):auditGlobal();document.getElementById('content').innerHTML=`<div class="pagehead"><div><h1>${journal?tr('journal'):tr('audit')}</h1><p>${journal?(lang==='ar'?'لكل حدث مالي موطن محاسبي واحد.':'Every financial event has one accounting home.'):(lang==='ar'?'كل اعتماد أو تعديل أو ترحيل قابل للتتبع.':'Every approval, override and posting is traceable.')}</p></div></div><div class="card panel">${journal?simpleTable(lang==='ar'?['الحدث','مدين','دائن','الضبط']:['Event','Debit','Credit','Control'],rows):simpleTable(lang==='ar'?['الوقت','الوحدة','الإجراء','المرجع']:['Time','Module','Action','Reference'],rows)}</div>`}
function auditGlobal(){let a=JSON.parse(localStorage.getItem('progacts_audit')||'[]');if(!a.length)a=[{time:new Date().toISOString(),module:1,action:'UPDATE',ref:'C-102'},{time:new Date().toISOString(),module:4,action:'APPROVAL',ref:'PO-24018'},{time:new Date().toISOString(),module:14,action:'INSERT',ref:'RFI-091'}];return a.slice(0,20).map(x=>[new Date(x.time).toLocaleString(lang==='ar'?'ar-AE':'en-GB'),`${lang==='ar'?'الوحدة':'Module'} ${x.module}`,x.action,x.ref])}
function simpleTable(h,rows){return `<div class="table"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="data">${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
renderLanding();if(location.hash==='#dashboard')enterApp();